// --------------------------------------
/// Sakura Compiler Version (generated by Cargo.toml, batch_version.nako3)
pub const SAKURA_VERSION: &str = "0.1.36";
// --------------------------------------