name: Test

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: test-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run tests
        run: cargo test
